name: coverage

on: [push]

jobs:
  build:

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt
        python -m pip install --upgrade -r requirements_ci.txt
    - name: Install module
      run: |
        export CYTHON_TRACE_NOGIL=1
        python setup.py build_ext --inplace --define CYTHON_TRACE_NOGIL
    - name: Test with pytest and coverage report
      run: |
        coverage run -m pytest tests
        coverage report
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_UPLOAD_TOKEN }} 
        fail_ci_if_error: true
        verbose: true
